FROM python:3.12-slim

WORKDIR /app

# ✅ 1. Instalar dependencias del sistema necesarias para compilar mysqlclient
RUN apt-get update && apt-get install -y \
    gcc \
    pkg-config \
    default-libmysqlclient-dev \
    build-essential \
    && rm -rf /var/lib/apt/lists/*

# ✅ 2. Asegurar que pip esté actualizado
RUN python -m ensurepip --upgrade && \
    pip install --upgrade pip setuptools wheel

# Set environment variables to optimize Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1 

COPY requirements.txt .

RUN pip install --no-cache -r requirements.txt


COPY . .
EXPOSE 8000

#Script
ENTRYPOINT ["sh","/entrypoint.sh"]