# Generated by Django 4.2 on 2025-03-22 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='medida',
            old_name='medida',
            new_name='nombre',
        ),
    ]
