# Generated by Django 4.2 on 2025-04-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_remove_producto_imagenes_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='medida',
        ),
        migrations.AddField(
            model_name='producto',
            name='medidas',
            field=models.ManyToManyField(null=True, related_name='Productos', to='api.medida'),
        ),
    ]
