# Generated by Django 4.2 on 2026-08-13 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_user_carrito_orden_remove_imagen_producto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
